repositories:
  - name: formbricks
    url: ghcr.io/formbricks/helm-charts
    oci: true

releases:
  - name: formbricks
    namespace: formbricks
    chart: formbricks/formbricks
    version: {{ requiredVersion "VERSION" }}
    values:
      - values.yaml.gotmpl
    set:
      - name: deployment.image.tag
        value: v{{ requiredVersion "VERSION" }}
