repositories:
  - name: helm-charts
    url: ghcr.io/formbricks/helm-charts
    oci: true

releases:
  - name: formbricks
    namespace: formbricks
    chart: helm-charts/formbricks
    version: ^1.0.0
    values:
      - values.yaml
    set:
      - name: deployment.image.tag
        value: v{{ requiredEnv "VERSION" }}
      - name: deployment.image.repository
        value: {{ requiredEnv "REPOSITORY" }}
      - name: deployment.env.S3_BUCKET_NAME.value
        value: {{ requiredEnv "FORMBRICKS_S3_BUCKET" }}
      - name: ingress.annotations."alb.ingress.kubernetes.io/certificate-arn"
        value: {{ requiredEnv "FORMBRICKS_INGRESS_CERT_ARN" }}
      - name: rbac.serviceAccount.annotations."eks.amazonaws.com/role-arn"
        value: {{ requiredEnv "FORMBRICKS_ROLE_ARN" }}
