name: Build and Deploy Formbricks

on:
  workflow_dispatch:
    inputs:
      deploy_experimental_image:
        description: 'Deploy the experimental image'
        required: false
        default: false
        type: boolean
  push:
    tags:
      - "v*"

jobs:
  docker-build:
    name: Build stable docker image
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/build-docker.yml

#  docker-build-experimental:
#    name: Build experimental docker image
#    if: ${{ github.event.inputs.deploy_experimental_image == 'true' }}
#    uses: ./.github/workflows/release-docker-github-experimental.yml

  helm-chart-release:
    name: Release Helm Chart
    uses: ./.github/workflows/release-helm-chart.yml
    needs:
      - docker






