name: Formbricks Helm Release

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'The version of the Helm chart to release'
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  helmfile-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: "eu-central-1"
      - name: Setup Cluster Access
        run: |
          aws eks update-kubeconfig --name formbricks-prod-eks --kubeconfig ./kubeconfig
          echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
          echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          AWS_REGION: eu-central-1
      - uses: helmfile/helmfile-action@v2
        env:
          VERSION: ${{ inputs.VERSION }}
          KUBECONFIG: "./kubeconfig"
        with:
          helmfile-version: 'v0.150.0'
          helm-version: 'v3.8.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff,
            https://github.com/jkroepke/helm-secrets
          helmfile-args: diff
          helmfile-auto-init: "false"
          helmfile-workdirectory: infra/deployment

