name: Release Helm Chart

on:
  release:
    types:
      - published

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract release version
        run: |
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Extract release version
        run: |
          echo "STRIPPED_VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Install YQ
        uses: dcarbone/install-yq-action@v1.3.1

      - name: Update Chart.yaml with new version
        run: |
          echo $STRIPPED_VERSION
          yq -i ".version = \"${VERSION#v}\"" helm-chart/formbricks/Chart.yaml
          yq -i ".appVersion = \"${VERSION}\"" helm-chart/formbricks/Chart.yaml

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          helm package helm-chart/formbricks --destination helm-chart/

      - name: install chart releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          install_only: true

      - name: make chart release
        run: |
          cr package helm-chart/formbricks
          cr upload --git-repo=k8s-test --release-name-template="v{{ .Version }}" -o formbricks --token ${{ secrets.GITHUB_TOKEN }} --skip-existing

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: .cr-release-packages/formbricks-${{ env.STRIPPED_VERSION }}.tgz

      - name: Update index.yaml
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add . && git commit -m "Updated helm chart"
          git fetch -a
          git checkout gh-pages
          git pull origin gh-pages
          cr index --git-repo=k8s-test --release-name-template="v{{ .Version }}" -o formbricks --token ${{ secrets.GITHUB_TOKEN }} -i ./index.yaml --push


#
#  publish-helm-chart:
#    needs: update-helm-chart
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Install Helm
#        run: |
#          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#          chmod 700 get_helm.sh
#          ./get_helm.sh
#
#      - name: Package Helm Chart
#        run: |
#          mkdir -p helm-charts
#          helm package helm --destination helm-charts
#
#      - name: Publish Helm Chart to GitHub Pages
#        uses: actions/configure-pages@v3
#
#      - name: Upload Helm Chart Artifact
#        uses: actions/upload-pages-artifact@v2
#        with:
#          path: ./helm-charts
#
#      - name: Deploy Helm Chart to GitHub Pages
#        uses: actions/deploy-pages@v2
