name: Github Actions Test
on:
  push:
    branches:
      - main
    paths:
      - helm-chart/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.AUTOMATION_BOT_ID }}
          private-key: ${{ secrets.AUTOMATION_BOT_KEY }}
